spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Slanemy/springclouddemo/
          search-paths: respo
          username: Slanemy
          password: slanemy@seu028
      label: master
server:
  port: 8007